# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bankmidtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bankmidtest
  pod 'SwiftSocket'
  pod 'CryptoSwift'

  target 'bankmidtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bankmidtestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
